export const INIT_BLOG_STATE = "INIT_BLOG_STATE";
export const LIST_BLOG_SUCCEEDED = "LIST_BLOG_SUCCEEDED";
export const LIST_BLOG_FAILED = "LIST_BLOG_FAILED";
export const LOAD_CARD_SUCCEEDED = "LOAD_CARD_SUCCEEDED";

export const UPDATE_CARD_STATE = "UPDATE_CARD_STATE";
export const UPDATE_CARD_NAME = "UPDATE_CARD_NAME";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const SAVE_OR_UPDATE_CARD = "SAVE_OR_UPDATE_CARD";

export const INIT_CUSTOM_AUDIENCE_STATE = "INIT_CUSTOM_AUDIENCE_STATE";

export const LIST_AD_ACCOUNT = "LIST_AD_ACCOUNT";
export const LIST_AD_ACCOUNT_SUCCEEDED = "LIST_AD_ACCOUNT_SUCCEEDED";
export const LIST_AD_ACCOUNT_FAILED = "LIST_AD_ACCOUNT_FAILED";
export const SELECTED_AD_ACCOUNT = "SELECTED_AD_ACCOUNT";

export const SELECTED_AUDIENCE_DATE = "SELECTED_AUDIENCE_DATE";

export const LIST_BRAND = "LIST_BRAND";
export const LIST_BRAND_SUCCEEDED = "LIST_BRAND_SUCCEEDED";
export const LIST_BRAND_FAILED = "LIST_BRAND_FAILED";
export const SELECTED_BRANDS = "SELECTED_BRANDS";

export const LIST_BUSINESS_MANAGER = "LIST_BUSINESS_MANAGER";
export const LIST_BUSINESS_MANAGER_SUCCEEDED = "LIST_BUSINESS_MANAGER_SUCCEEDED";
export const LIST_BUSINESS_MANAGER_FAILED = "LIST_BUSINESS_MANAGER_FAILED";
export const SELECTED_BUSINESS_MANAGER = "SELECTED_BUSINESS_MANAGER";

export const LIST_BUSINESS_UNIT = "LIST_BUSINESS_UNIT";
export const LIST_BUSINESS_UNIT_SUCCEEDED = "LIST_BUSINESS_UNIT_SUCCEEDED";
export const LIST_BUSINESS_UNIT_FAILED = "LIST_BUSINESS_UNIT_FAILED";
export const SELECTED_BUSINESS_UNIT = "SELECTED_BUSINESS_UNIT";

export const LIST_DEPARTMENTS = "LIST_DEPARTMENTS";
export const LIST_DEPARTMENTS_SUCCEEDED = "LIST_DEPARTMENTS_SUCCEEDED";
export const LIST_DEPARTMENTS_FAILED = "LIST_DEPARTMENTS_FAILED";
export const SELECTED_DEPARTMENTS = "SELECTED_DEPARTMENTS";

export const SEND_T1_QUERY = "SEND_T1_QUERY";
export const SEND_T1_QUERY_ASYNC = "SEND_T1_QUERY_ASYNC";
export const SEND_T1_QUERY_SUCCEEDED = "SEND_T1_QUERY_SUCCEEDED";
export const SEND_T1_QUERY_FAILED = "SEND_T1_QUERY_FAILED";

export const LIST_T1_ATHENA_JOB = "LIST_T1_ATHENA_JOB";
export const LIST_T1_ATHENA_JOB_SUCCEEDED = "LIST_T1_ATHENA_JOB_SUCCEEDED";
export const LIST_T1_ATHENA_JOB_FAILED = "LIST_T1_ATHENA_JOB_FAILED";

export const RESET_AUDIENCE_FORM = "RESET_AUDIENCE_FORM";
export const DELETE_AUDIENCE = "DELETE_AUDIENCE";

export const SELECTED_T1_SVOC_CRITERIAS = "SELECTED_T1_SVOC_CRITERIAS";

export const UPDATE_AUDIENCE_NAME_SYNC = "UPDATE_AUDIENCE_NAME_SYNC";