# Generated by Django 3.1.6 on 2021-09-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('status', models.BooleanField(default=True, help_text='ACTIVE OR INACTIVE')),
                ('content', models.CharField(default='', max_length=4000)),
                ('category', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
